### ISSUE TITLE
Hooks/eden dependencies

### ISSUE THREAD

**Issue by imKota** [Ouroboros/JuusanKoubou#2]
```
1>c1xx : fatal error C1083: Не удается открыть файл источник: ..\..\..\..\MyLib\src\my_api.cpp: No such file or directory,
1>c1xx : fatal error C1083: Не удается открыть файл источник: ..\..\..\..\MyLib\src\my_crtadd.cpp: No such file or directory,
```

```
#include "my_headers.h"
#include "AudioPlayback.h"
#include "vorbishook.cpp"
#include "gal_common.h"
MyLib\src\my_api.cpp
MyLib\src\my_crtadd.cpp
```

**Comment by imKota** [comment]
@Ouroboros ??

**Comment by Ouroboros** [comment]
?

**Comment by imKota** [comment]
@Ouroboros Could you share the dependencies for this project https://github.com/Ouroboros/JuusanKoubou/tree/master/Source/Hooks/eden ? It is possible to my mail, or as you prefer.

**Comment by Ouroboros** [comment]
Sorry but I have no plan to make them public

**Comment by imKota** [comment]
@Ouroboros why not?

**Comment by imKota** [comment]
@Ouroboros Ok. Do you have a telegram/WeChat ? I have a couple of questions. Not public.

**Comment by Ouroboros** [comment]
> @Ouroboros Not public. Only for personal usage

You can use another hook library

https://github.com/kubo/funchook/wiki/List-of-API-Hook-Libraries

**Comment by imKota** [comment]
@Ouroboros hello again!
I still hope for you ... Can you share the dependencies after all?
For personal use, they will not get into the network.
