### ISSUE TITLE
QLIE Packer FilePackVer3.0 game Koiken Otome

### ISSUE THREAD

**Issue by imKota** [Ouroboros/JuusanKoubou#3]
Hello!
Can you add support game "Koiken Otome" and rebuild this project 
https://github.com/Ouroboros/JuusanKoubou/tree/master/Source/Tools/CSharp/Packer

Repack working, but files in archive is corrupted and not reading. 
Although the structure of files and folders in the archive is correct.

![image](https://user-images.githubusercontent.com/24241471/56352594-3dd96b80-61d8-11e9-98c6-8b52baadadc8.png)

**Comment by Ouroboros** [comment]
Sorry, this tool is not maintained anymore.

**Comment by imKota** [comment]
@Ouroboros Then maybe you will send me these files, and I will sort it out further?
These are dependencies for QLIE.dll
```
#include "gal_common.h"
#include "Mem.cpp"
#include "my_headers.h"
#include "../plugin_common.h"

```

**Comment by Ouroboros** [comment]
As I said before, I have no plan to make them public, you can use another hook library.
